name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          headed: true
          run: npx cypress run --env allure=true
      - name: Generate Allure report
            uses: QuintilianoNery/action-allure-report-V2@0.2.0
