name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          headed: true
          run: npx cypress run --env allure=true
      - name: Allure  generate
        run: allure generate allure-results
      - name: Deploy report
              uses: JamesIves/github-pages-deploy-action@4.1.4
              if: always()
              with:
                  branch: master
                  folder: ./allure-report